export { default as header } from './headerStyle';
export { default as footer } from './footerStyle';
export { default as icon } from './iconStyle';
export { default as menu } from './menuStyle';
export { default as tooltip } from './tooltipStyle';
export { default as contact } from './contactStyle';
export { default as home } from './homeStyle';
export { default as about } from './aboutStyle';
export { default as app } from './appStyle';
